using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Engine.Globals
{
    /// <summary>
    /// rus: Базовые адреса для смещений в памяти.
    /// eng: Base adresses for offssets memory
    /// </summary>
    public class Netvars
    {
        public static int cs_gamerules_data = 0x0;
        public static int m_ArmorValue = 0xB378;
        public static int m_Collision = 0x320;
        public static int m_CollisionGroup = 0x474;
        public static int m_Local = 0x2FBC;
        public static int m_MoveType = 0x25C;
        public static int m_OriginalOwnerXuidHigh = 0x31C4;
        public static int m_OriginalOwnerXuidLow = 0x31C0;
        public static int m_SurvivalGameRuleDecisionTypes = 0x1328;
        public static int m_SurvivalRules = 0xD00;
        public static int m_aimPunchAngle = 0x302C;
        public static int m_aimPunchAngleVel = 0x3038;
        public static int m_angEyeAnglesX = 0xB37C;
        public static int m_angEyeAnglesY = 0xB380;
        public static int m_bBombDefused = 0x29B0;
        public static int m_bBombPlanted = 0x9A5;
        public static int m_bBombTicking = 0x2980;
        public static int m_bFreezePeriod = 0x20;
        public static int m_bGunGameImmunity = 0x3944;
        public static int m_bHasDefuser = 0xB388;
        public static int m_bHasHelmet = 0xB36C;
        public static int m_bInReload = 0x32A5;
        public static int m_bIsDefusing = 0x3930;
        public static int m_bIsQueuedMatchmaking = 0x74;
        public static int m_bIsScoped = 0x3928;
        public static int m_bIsValveDS = 0x7C;
        public static int m_bSpotted = 0x93D;
        public static int m_bSpottedByMask = 0x980;
        public static int m_bStartedArming = 0x33F0;
        public static int m_bUseCustomAutoExposureMax = 0x9D9;
        public static int m_bUseCustomAutoExposureMin = 0x9D8;
        public static int m_bUseCustomBloomScale = 0x9DA;
        public static int m_clrRender = 0x70;
        public static int m_dwBoneMatrix = 0x26A8;
        public static int m_fAccuracyPenalty = 0x3330;
        public static int m_fFlags = 0x104;
        public static int m_flC4Blow = 0x2990;
        public static int m_flCustomAutoExposureMax = 0x9E0;
        public static int m_flCustomAutoExposureMin = 0x9DC;
        public static int m_flCustomBloomScale = 0x9E4;
        public static int m_flDefuseCountDown = 0x29AC;
        public static int m_flDefuseLength = 0x29A8;
        public static int m_flFallbackWear = 0x31D0;
        public static int m_flFlashDuration = 0xA420;
        public static int m_flFlashMaxAlpha = 0xA41C;
        public static int m_flLastBoneSetupTime = 0x2924;
        public static int m_flLowerBodyYawTarget = 0x3A90;
        public static int m_flNextAttack = 0x2D70;
        public static int m_flNextPrimaryAttack = 0x3238;
        public static int m_flSimulationTime = 0x268;
        public static int m_flTimerLength = 0x2994;
        public static int m_hActiveWeapon = 0x2EF8;
        public static int m_hBombDefuser = 0x29B4;
        public static int m_hMyWeapons = 0x2DF8;
        public static int m_hObserverTarget = 0x338C;
        public static int m_hOwner = 0x29CC;
        public static int m_hOwnerEntity = 0x14C;
        public static int m_hViewModel = 0x32F8;
        public static int m_iAccountID = 0x2FC8;
        public static int m_iClip1 = 0x3264;
        public static int m_iCompetitiveRanking = 0x1A84;
        public static int m_iCompetitiveWins = 0x1B88;
        public static int m_iCrosshairId = 0xB3E4;
        public static int m_iDefaultFOV = 0x332C;
        public static int m_iEntityQuality = 0x2FAC;
        public static int m_iFOVStart = 0x31E8;
        public static int m_iGlowIndex = 0xA438;
        public static int m_iHealth = 0x100;
        public static int m_iItemDefinitionIndex = 0x2FAA;
        public static int m_iItemIDHigh = 0x2FC0;
        public static int m_iMostRecentModelBoneCounter = 0x2690;
        public static int m_iObserverMode = 0x3378;
        public static int m_iShotsFired = 0xA390;
        public static int m_iState = 0x3258;
        public static int m_iTeamNum = 0xF4;
        public static int m_lifeState = 0x25F;
        public static int m_nBombSite = 0x2984;
        public static int m_nFallbackPaintKit = 0x31C8;
        public static int m_nFallbackSeed = 0x31CC;
        public static int m_nFallbackStatTrak = 0x31D4;
        public static int m_nForceBone = 0x268C;
        public static int m_nTickBase = 0x3430;
        public static int m_nViewModelIndex = 0x29C0;
        public static int m_rgflCoordinateFrame = 0x444;
        public static int m_szCustomName = 0x303C;
        public static int m_szLastPlaceName = 0x35B4;
        public static int m_thirdPersonViewAngles = 0x31D8;
        public static int m_vecOrigin = 0x138;
        public static int m_vecVelocity = 0x114;
        public static int m_vecViewOffset = 0x108;
        public static int m_viewPunchAngle = 0x3020;
        public static int m_zoomLevel = 0x33D0;
    }
    public static class signatures
    {
        public static int anim_overlays = 0x2980;
        public static int clientstate_choked_commands = 0x4D30;
        public static int clientstate_delta_ticks = 0x174;
        public static int clientstate_last_outgoing_command = 0x4D2C;
        public static int clientstate_net_channel = 0x9C;
        public static int convar_name_hash_table = 0x2F0F8;
        public static int dwClientState = 0x58EFE4;
        public static int dwClientState_GetLocalPlayer = 0x180;
        public static int dwClientState_IsHLTV = 0x4D48;
        public static int dwClientState_Map = 0x28C;
        public static int dwClientState_MapDirectory = 0x188;
        public static int dwClientState_MaxPlayer = 0x388;
        public static int dwClientState_PlayerInfo = 0x52C0;
        public static int dwClientState_State = 0x108;
        public static int dwClientState_ViewAngles = 0x4D90;
        public static int dwEntityList = 0x4DA3F44;
        public static int dwForceAttack = 0x31D54A4;
        public static int dwForceAttack2 = 0x31D54B0;
        public static int dwForceBackward = 0x31D54F8;
        public static int dwForceForward = 0x31D5504;
        public static int dwForceJump = 0x524DEA4;
        public static int dwForceLeft = 0x31D5480;
        public static int dwForceRight = 0x31D5474;
        public static int dwGameDir = 0x62D7F8;
        public static int dwGameRulesProxy = 0x52C118C;
        public static int dwGetAllClasses = 0xDB3F9C;
        public static int dwGlobalVars = 0x58ECE8;
        public static int dwGlowObjectManager = 0x52EC558;
        public static int dwInput = 0x51F5528;
        public static int dwInterfaceLinkList = 0x946B44;
        public static int dwLocalPlayer = 0xD8C2CC;
        public static int dwMouseEnable = 0xD91E70;
        public static int dwMouseEnablePtr = 0xD91E40;
        public static int dwPlayerResource = 0x31D3800;
        public static int dwRadarBase = 0x51D8CBC;
        public static int dwSensitivity = 0xD91D0C;
        public static int dwSensitivityPtr = 0xD91CE0;
        public static int dwSetClanTag = 0x8A1B0;
        public static int dwViewMatrix = 0x4D95844;
        public static int dwWeaponTable = 0x51F5FE8;
        public static int dwWeaponTableIndex = 0x325C;
        public static int dwYawPtr = 0xD91AD0;
        public static int dwZoomSensitivityRatioPtr = 0xD96D70;
        public static int dwbSendPackets = 0xD749A;
        public static int dwppDirect3DDevice9 = 0xA7050;
        public static int find_hud_element = 0x2653E320;
        public static int force_update_spectator_glow = 0x3AD962;
        public static int interface_engine_cvar = 0x3E9EC;
        public static int is_c4_owner = 0x3BA430;
        public static int m_bDormant = 0xED;
        public static int m_flSpawnTime = 0xA370;
        public static int m_pStudioHdr = 0x294C;
        public static int m_pitchClassPtr = 0x51D8F58;
        public static int m_yawClassPtr = 0xD91AD0;
        public static int model_ambient_min = 0x59205C;
        public static int set_abs_angles = 0x1DF9C0;
        public static int set_abs_origin = 0x1DF800;
    }
}